### ISSUE TITLE
Clickable links in zk 101 article's reference section are not easily identifiable

### ISSUE THREAD

**Issue by 0xpili** [web3citizenxyz/web3citizen#4]
I noticed that the links in the "References" section in the zk 101 article are not highlighted, making it difficult for users to identify them as clickable links.

Expected behavior: Links should be clearly highlighted, either by underlining or changing the text color, to indicate that they are clickable.

![image](https://github.com/user-attachments/assets/dee56dc4-11ad-49f5-a1bc-2cf9fa3270a2)

**Comment by unfoquito** [comment]
Fixed in last PR
